#!/bin/bash

if [ "$#" -lt "1" ]
then
    echo "## USAGE: $0 FIELD_NAME [FILE]"
    echo "# assuming rows of format FIELD_NAME=..."
    echo "# this extracts the RHS of all such fields as a column."
    echo "# (actually this supports partial name matching as well)"
    echo "# (including the = symbol is OPTIONAL)"
    exit 1
fi

#for ((i=0;i<$#;++i)) ; do
if [ "$#" -eq "2" ]
then
    cat -u $2 | grep --line-buffered "$1" | grep --line-buffered "=" | stdbuf -oL cut -d"=" -f2
else
    cat -u /dev/stdin | grep --line-buffered "$1" | grep --line-buffered "=" | stdbuf -oL cut -d"=" -f2
fi
